name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Test Java ${{ matrix.java }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 1  # Run sequentially to avoid resource contention
      matrix:
        java: ['11', '17', '21']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Install Babashka
        run: |
          curl -sLO https://raw.githubusercontent.com/babashka/babashka/master/install
          chmod +x install
          sudo ./install

      - name: Install Leiningen
        run: |
          wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
          chmod +x lein
          sudo mv lein /usr/local/bin/
          lein version

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.lein
          key: ${{ runner.os }}-lein-${{ hashFiles('**/project.clj') }}
          restore-keys: |
            ${{ runner.os }}-lein-

      - name: Download dependencies
        run: lein deps

      - name: Run tests with bb
        if: matrix.java != '17'
        run: bb test:all

      - name: Run coverage with bb
        if: matrix.java == '17'
        run: bb coverage --codecov

      - name: Upload coverage to Codecov
        if: matrix.java == '17'
        uses: codecov/codecov-action@v4
        with:
          file: ./target/coverage/codecov.json
          flags: unittests
          name: codecov-datacamp
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage report
        if: always() && matrix.java == '17'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: target/coverage/
          if-no-files-found: ignore
